function [Par,beta] = ParSet_compare(Nmas)
    if Nmas<=17
        Par.var          = 11;
        Par.maxIter      = 80;
        Par.tol          = 1e-4;
        Par.mu           = 100;
        Par.rho          = 1.1;
        Par.initIterNum  = 20;
        beta             = 1000;
        Par.wTV          = [1,0.5,0.5,1];
        Par.PwlsInit     = 1;
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 80;
    elseif Nmas<=40
        Par.var          = 11;
        Par.maxIter      = 80;
        Par.tol          = 1e-4;
        Par.mu           = 100;
        Par.rho          = 1.1;
        Par.initIterNum  = 20;
        beta             = 2000;
        Par.wTV          = [1,0.5,0.5,1];
        Par.PwlsInit     = 1;
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 100;
    elseif Nmas<=60
        Par.var          = 11;
        Par.maxIter      = 80;
        Par.tol          = 1e-4;
        Par.mu           = 100;
        Par.rho          = 1.1;
        Par.initIterNum  = 20;
        beta             = 2500;
        Par.wTV          = [1,0.5,0.5,1];
        Par.PwlsInit     = 1;
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 100;
    elseif Nmas<=100
        Par.var          = 11;
        Par.maxIter      = 80;
        Par.tol          = 1e-4;
        Par.mu           = 100;
        Par.rho          = 1.1;
        Par.initIterNum  = 20;
        beta             = 20000;
        Par.wTV          = [1,0.5,0.5,1];
        Par.PwlsInit     = 1;
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 100;
    end
