function Par = ParSetIMAP_TV(Nmas,InitPWLS)
% 二阶 logsum 梯度方法的参数生成
if nargin<2||InitPWLS==0
    if Nmas<=17
        Par.var          = 11;
        Par.maxIter      = 20;
        Par.tol          = 1e-5;
        Par.mu           = 100;
        Par.rho          = 1.05;
        Par.beta         = 180;
        Par.wTV          = [1,0.5,0.5,1];
        Par.kappa        = 2294.5;
        Par.pwlsBeta     =  15;% 先前用的是80， 只是在Anthoro1这个数据上改成了15 
    elseif Nmas<=40
        Par.var          = 11;
        Par.maxIter      = 30;
        Par.tol          = 1e-5;
        Par.mu           = 150;
        Par.rho          = 1.05;
        Par.beta         = 150;
        Par.wTV          = [1,0.5,0.5,1];
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 20;
    elseif Nmas<=60
        Par.var          = 11;
        Par.maxIter      = 30;
        Par.tol          = 1e-5;
        Par.mu           = 150;
        Par.rho          = 1.05;
        Par.beta         = 150;
        Par.wTV          = [1,0.5,0.5,1];
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 20;
    elseif Nmas<=100
        Par.var          = 11;
        Par.maxIter      = 30;
        Par.tol          = 1e-5;
        Par.mu           = 100;
        Par.rho          = 1.1;
        Par.beta         = 150;
        Par.wTV          = [1,0.5,0.5,1];
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 20;
    end
else
    Par.PwlsInit=1 ;
    if Nmas<=17
        Par.var          = 11;
        Par.maxIter      = 20;
        Par.tol          = 1e-5;
        Par.mu           = 100;
        Par.rho          = 1.05;
        Par.beta         = 150;
        Par.wTV          = [1,0.5,0.5,1];
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 15;
    elseif Nmas<=40
        Par.var          = 11;
        Par.maxIter      = 30;
        Par.tol          = 1e-5;
        Par.mu           = 150;
        Par.rho          = 1.05;
        Par.beta         = 150;
        Par.wTV          = [1,0.5,0.5,1];
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 20;
    elseif Nmas<=60
        Par.var          = 11;
        Par.maxIter      = 30;
        Par.tol          = 1e-5;
        Par.mu           = 150;
        Par.rho          = 1.05;
        Par.beta         = 250;
        Par.wTV          = [1,0.5,0.5,1];
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 20;
    elseif Nmas<=100
        Par.var          = 11;
        Par.maxIter      = 30;
        Par.tol          = 1e-5;
        Par.mu           = 100;
        Par.rho          = 1.1;
        Par.beta         = 150;
        Par.wTV          = [1,0.5,0.5,1];
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 20;
    end
end
end