function [Par,b] = ParSet(Nmas)
% 二阶 logsum 梯度方法的参数生成
    if Nmas<=17
        Par.sig          = 11;
        Par.maxIter      = 60;
        Par.tol          = 1e-8;
        Par.mu           = 100;
        Par.rho          = 1.1;
        Par.initIter     = 20;
        b                = 1/1.3;  
        Par.wTV          = [1,0.5,0.5,1];
        Par.PwlsInit     = 1;
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 60; 
        Par.Just         = 8.5;
    elseif Nmas<=40
        Par.sig          = 11;
        Par.maxIter      = 60;
        Par.tol          = 1e-5;
        Par.mu           = 100;
        Par.rho          = 1.1;
        Par.initIter     = 20;
        b                = 1/1.3;
        Par.wTV          = [1,0.5,0.5,1];
        Par.PwlsInit     = 0.8;
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 40; 
        Par.Just         = 8.2;
    elseif Nmas<=60
        Par.sig          = 11;
        Par.maxIter      = 60;
        Par.tol          = 1e-5;
        Par.mu           = 100;
        Par.rho          = 1.1;
        Par.initIter     = 20;
        b                = 1/1.5;
        Par.wTV          = [1,0.5,0.5,1];
        Par.PwlsInit     = 1;
        Par.kappa        = 2294.5;
        Par.pwlsBeta     = 80; 
        Par.Just         = 8;
    end
